### ISSUE TITLE
Wrong resolution with rootless paths

### ISSUE THREAD

**Issue by pchampin** [oxigraph/oxiri#2]
Consider the following base IRI `tag:a-b` and the following relative IRI ref `c-d`. Resolving the latter against the former should result in `tag:c-d`, but oxiri gives `tag:/c-d`.

I checked the resolution algorithm (https://datatracker.ietf.org/doc/html/rfc3986#section-5.2) and I am convinced that my assumption above is correct, and that oxiri is wrong.

Preparing a PR to fix this.

**Comment by Tpt** [comment]
Indeed, thank you!
